### ISSUE TITLE
[Backend] Modeller för fotogalleri

### ISSUE THREAD

**Issue by jesperlundqvist** [medieteknik-kth/medieteknik.com#186]

**Comment by jesperlundqvist** [comment]
Tre versioner av varje bild:
 * Thumbnail
 * Mellanstor
 * Original

**Comment by jesperlundqvist** [comment]
Varje bild:
- Tillhör album
- URL
- Fotograf
- Fotodatum
- Om bilden måste creddas
- Om bilder får redigera

Varje album:
- Lista av bilder
- Namn
- Datum (skapat)
- Datum (senast redigerat)
- nØllevänlig

**Comment by Lunkers** [comment]
Behöver vi verkligen "tillhör album" på bilder? om jag förstått SQLAlchemy rätt så skapar den en relationstabell på enkelriktade associationer utan problem.

**Comment by jesperlundqvist** [comment]
> Behöver vi verkligen "tillhör album" på bilder? om jag förstått SQLAlchemy rätt så skapar den en relationstabell på enkelriktade associationer utan problem.

Ja, det var det jag menade! Alltså att varje bild tillhör ett album

**Comment by Lunkers** [comment]
Precis, men modellen för bilder kommer inte behöva det fältet (iallafall inte explicit i koden)
