### ISSUE TITLE
Skapa egen videospelare

### ISSUE THREAD

**Issue by rrudling** [medieteknik-kth/medieteknik.com#190]

**Comment by jesperlundqvist** [comment]
* Koda om uppladdade videofiler
* Design för videospelare
* Design för videogalleri
* Spellistor (en video kan vara i en eller flera spellistor)
* Taggar på spellistor (t.ex. Mottagningen 2020, Halloweengasquen)
* Vissa filmer ska bara synas för inloggade
* Taggade som nØllevänliga

Videomodell:
* Titel
* Datum
* Beskrivning
* Videolängd
* Vilka spellistor den är kopplad till
* Lista av alla som varit med (eventuellt rolllista) (fritext eller användare/nämnd?)

Spellistor:
* Datum
* Taggar

KomN/INPHO laddar upp videor:
* Oftast flera samtidigt
* Automatiskt välja thumbnails eller ladda upp själv

Titta på videor:
* Välja uppspelningshastighet
* Upptäcka spellistor (sortera och filtrera)
* Stjärnmarkera/titta senare

**Comment by jesperlundqvist** [comment]
Koppla video till nämnd eller person
