### ISSUE TITLE
[Frontend] Event

### ISSUE THREAD

**Issue by jesperlundqvist** [medieteknik-kth/medieteknik.com#49]

**Comment by rrudling** [comment]
- Hur ser ett event ut?
- Hur ser en samling event ut?
- Hur ser ett event ut på en nämndsida?
- Eventundantag ?

**Comment by rrudling** [comment]
- Drafts av event
- Schemalagda publiceringar av event

**Comment by Lunkers** [comment]
Innehåller det här också redigering/skapande av event, eller är det bara presentation?

**Comment by jesperlundqvist** [comment]
> Innehåller det här också redigering/skapande av event, eller är det bara presentation?

Nej, det är bara presentationen just nu!
