### ISSUE TITLE
[Backend] Event

### ISSUE THREAD

**Issue by Lunkers** [medieteknik-kth/medieteknik.com#50]
Se till att databasen har en modell för event; struktur finns redan på sin egen branch, men det är bättre att radera den och bygga från master istället, på grund av stora ändringar.

**Comment by jesperlundqvist** [comment]
Endpoints för:
- Lista alla events (med filter för nämnd, kanske även datum?)
- Ett enskilt event
- Skapa nytt event
- Ändra event
- Ta bort event

**Comment by Lunkers** [comment]
Lägg till följande i modellen:

- Nämnd som arrangerar (relation)
- Omslagsbild (databas + uppladdning)
- Facebook-länk (till eventsidan)
